name: marketsutra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  url_launcher: ^6.1.10
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  google_sign_in: ^6.3.0
  image_picker: ^1.2.0
  font_awesome_flutter: ^10.7.0
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  webview_flutter: ^4.13.0
  connectivity_plus: ^6.0.3
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/wallpaper.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/google_light.png
    - assets/indian_emblem.png
    - assets/icons/turtle.jpg
    - assets/icons/bull.png
    - assets/icons/whale.png
    - assets/icons/bear.jpeg
    - assets/icons/dear.jpg
    - assets/upi_logo.jpg
    - assets/icons/portfolio.png
    - assets/icons/wallpaper.jpg
    - assets/apple.jpg
